### ISSUE TITLE
Dependency not properly installed

### ISSUE THREAD

**Issue by ericdaoo** [bryanchw/Traditional-Chinese-Stopwords-and-Punctuations-Library#1]
Hi, it seems that after installing the package via "pip install TCSP", the stopwords-zht.txt file dependency is not installed. Because of this, the read_stopwords_list() function does not work. However, downloading your package from GitHub and inserting it within my python packages directory will make the module work. 

I'm fairly new to custom made python packages and tried to play around with things to the find the solution by forking your repository. It seems that the problem likely stems from the setup.py file not specifying all the proper dependencies to be installed when a user does pip install. Also, it's possible that placing the read_stopwords_list() module function within the __init__.py file, could possibly cause issues. 

Anywho, was wondering if you had any ideas? I know it's not a big issue, but it piqued my interest and now I want to know what is causing the issue haha.

**Comment by bryanchw** [comment]
Hi @ericdaoo, I don't think it is related to dependency but I may be wrong. May I know which version of Python you were using and the error message you got? I think this could be a reading resource issue but to avoid any potential problem, I fixed it by putting the stopwords list in the __init__.py. It seems to be working fine now.
